final `check if tag is on main branch`

diff --git a/.github/workflows/workflow2.yml b/.github/workflows/workflow2.yml
--- a/.github/workflows/workflow2.yml
+++ b/.github/workflows/workflow2.yml
@@ -17,7 +17,6 @@ jobs:
 
   workflow2:
     needs: pre-workflow2
-
     runs-on: ubuntu-latest
 
     steps:
@@ -25,34 +24,16 @@ jobs:
         with:
           fetch-depth: 0 # load the entire history, otherwise git will not find the branch
 
-      - name: Workflow2
-        run: echo "Hello Workflow2!"
-
-      # - name: Dump GitHub context
-      #   env:
-      #     GITHUB_CONTEXT: ${{ toJson(github) }}
-      #   run: echo "$GITHUB_CONTEXT"
-
-      - name: Find branch for tag
-        run: |
-          BRANCHES=$(git branch -r --contains ${{ github.sha }} | grep -v HEAD | sed 's/origin\///')
-          DEFAULT=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
-          for BRANCH in $BRANCHES; do
-            if [[ "$BRANCH" != "$DEFAULT" && "$BRANCH" != "main" ]]; then
-              echo "BRANCH=$BRANCH" >> $GITHUB_ENV
-              exit 0
-            fi
-          done
-          echo "BRANCH=$DEFAULT" >> $GITHUB_ENV
-
-      - name: Print branch
-        run: echo "Tag was created from branch $BRANCH"
-
       - name: Check if tag is on main branch
         run: |
-          branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
-          echo "Branch is $branch."
-          if [ "$branch" != "main" ]; then
-            echo "Error: Tag must be on main branch!"
-            exit 1
-          fi
+          branches=$(git branch -r --contains ${{ github.sha }} | grep -v HEAD | sed 's/origin\///')
+          default_branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
+          for branch in $branches; do
+            if [[ "$branch" != "$default_branch" && "$branch" != "main" ]]; then
+              echo "Error: Tag must be on main branch!"
+              exit 1
+            fi
+          done
+      
+      - name: Workflow2
+        run: echo "Hello Workflow2!"
