updated

diff --git a/.github/workflows/workflow2.yml b/.github/workflows/workflow2.yml
--- a/.github/workflows/workflow2.yml
+++ b/.github/workflows/workflow2.yml
@@ -22,11 +22,22 @@ jobs:
 
     steps:
       - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # load the entire history, otherwise git will not find the branch
 
       - name: Workflow2
         run: echo "Hello Workflow2!"
 
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+
       - name: Check if tag is on main branch
         run: |
-          echo "Branch1 is $(git branch --show-current)"
-          echo "Branch2 is $(git branch -r --contains $GITHUB_REF)"
+          branch=$(git branch --show-current)
+          echo "Branch is $branch."
+          if [ "$branch" != "main" ]; then
+            echo "Error: Tag must be on main branch!"
+            exit 1
+          fi
