updated

diff --git a/.github/workflows/workflow2.yml b/.github/workflows/workflow2.yml
--- a/.github/workflows/workflow2.yml
+++ b/.github/workflows/workflow2.yml
@@ -26,15 +26,14 @@ jobs:
 
       - name: Check if tag is on main branch
         run: |
-          branches=$(git branch -r --contains ${{ github.sha }} | grep -v HEAD | sed 's/origin\///')
           default_branch=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
           echo "Default branch is $default_branch."
-          for branch in $branches; do
-            if [[ "$branch" != "$default_branch" && "$branch" != "main" ]]; then
-              echo "Error: Tag must be on main branch!"
-              exit 1
-            fi
-          done
+          current_branch=$(git branch --show-current)
+          echo "Current Branch is $current_branch."
+          if [ "$default_branch" != "main" ]; then
+            echo "Error: Tag must be on main branch!"
+            exit 1
+          fi
 
       - name: Workflow2
         run: echo "Hello Workflow2!"
